# Generated by Django 5.0 on 2025-01-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='consent',
            name='consent_file',
        ),
        migrations.RemoveField(
            model_name='consent',
            name='consent_text',
        ),
        migrations.AlterField(
            model_name='consent',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
