# Generated by Django 5.0 on 2025-01-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_telegram_id_user_telegram_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
