# Generated by Django 5.0 on 2025-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='content',
            field=models.TextField(blank=True, max_length=200, verbose_name='вещи на хранении'),
        ),
    ]
