# Generated by Django 5.0 on 2025-01-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contract_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('admin', 'Звонок администратору'), ('courier', 'Звонок курьеру')], max_length=10, verbose_name='Тип звонка')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запроса')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан ли запрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на звонок',
                'verbose_name_plural': 'Запросы на звонки',
            },
        ),
    ]
