# Generated by Django 5.0 on 2025-01-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='owner_phone',
        ),
    ]
