# Generated by Django 5.0 on 2025-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contract_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='pre_order',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Предзаказ'),
        ),
    ]
