# Generated by Django 5.0 on 2025-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_call_pre_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Переход по ссылке',
                'verbose_name_plural': 'Переходы по ссылкам',
            },
        ),
    ]
